import React from 'react';
import { Sparkles, AlertTriangle, Lightbulb, Loader2, Info } from 'lucide-react';

interface AIInsightsProps {
  insights: {
    keyInsights: string[];
    risks: string[];
    recommendations: string[];
  } | null;
  loading: boolean;
  onRetry: () => void;
}

export default function AIInsights({ insights, loading, onRetry }: AIInsightsProps) {
  if (loading) {
    return (
      <div className="glass-card p-8 flex flex-col items-center justify-center min-h-[200px]">
        <Loader2 className="w-8 h-8 text-blue-500 animate-spin mb-4" />
        <p className="text-slate-400 animate-pulse">Analyzing your data with Gemini AI...</p>
      </div>
    );
  }

  if (!insights) {
    return (
      <div className="glass-card p-8 text-center">
        <Sparkles className="w-10 h-10 text-blue-400 mx-auto mb-4" />
        <h3 className="text-xl font-bold text-white mb-2">AI Data Insights</h3>
        <p className="text-slate-400 mb-6">Unlock hidden trends and risks in your data using AI.</p>
        <button 
          onClick={onRetry}
          className="px-6 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white rounded-full font-medium transition-all shadow-lg shadow-blue-500/20"
        >
          Generate Insights
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <Sparkles className="text-blue-400" />
          AI Insights
          <span className="text-[10px] bg-blue-500/10 text-blue-400 px-2 py-0.5 rounded border border-blue-500/20 uppercase tracking-widest ml-2">Beta</span>
        </h2>
        <div className="group relative">
           <Info size={16} className="text-slate-500 cursor-help" />
           <div className="absolute bottom-full right-0 mb-2 w-64 p-3 bg-slate-800 text-xs text-slate-300 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none border border-slate-700 shadow-xl z-50">
             Insights are generated by Gemini AI base on summarized data. Always verify critical business decisions.
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Key Insights */}
        <div className="glass-card p-6 border-l-4 border-l-blue-500">
          <div className="flex items-center gap-2 mb-4 text-blue-400">
            <Sparkles size={20} />
            <h3 className="font-bold uppercase tracking-wider text-sm">Key Trends</h3>
          </div>
          <ul className="space-y-3">
            {insights.keyInsights.map((item, i) => (
              <li key={i} className="text-slate-300 text-sm flex gap-2">
                <span className="text-blue-500 font-bold">•</span>
                {item}
              </li>
            ))}
          </ul>
        </div>

        {/* Risks */}
        <div className="glass-card p-6 border-l-4 border-l-amber-500">
          <div className="flex items-center gap-2 mb-4 text-amber-400">
            <AlertTriangle size={20} />
            <h3 className="font-bold uppercase tracking-wider text-sm">Potential Risks</h3>
          </div>
          <ul className="space-y-3">
            {insights.risks.map((item, i) => (
              <li key={i} className="text-slate-300 text-sm flex gap-2">
                <span className="text-amber-500 font-bold">•</span>
                {item}
              </li>
            ))}
          </ul>
        </div>

        {/* Recommendations */}
        <div className="glass-card p-6 border-l-4 border-l-emerald-500">
          <div className="flex items-center gap-2 mb-4 text-emerald-400">
            <Lightbulb size={20} />
            <h3 className="font-bold uppercase tracking-wider text-sm">Actions</h3>
          </div>
          <ul className="space-y-3">
            {insights.recommendations.map((item, i) => (
              <li key={i} className="text-slate-300 text-sm flex gap-2">
                <span className="text-emerald-500 font-bold">•</span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>
      
      <p className="text-center text-slate-600 text-[10px] italic">
        * AI-generated insights may contain inaccuracies. Please use as a reference.
      </p>
    </div>
  );
}
